name: hosta
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  http: ^1.3.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  google_mobile_ads: ^6.0.0
  geocoding: ^3.0.0
  location: ^8.0.0
  google_maps_flutter: ^2.12.2
  flutter_polyline_points: ^2.1.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/images/fonts/Poppins-Regular.ttf
        - asset: assets/images/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/images/fonts/Poppins-Thin.ttf
          weight: 100

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/logo-hosta.png"
